GENOME_MIN_LAYERS = 1
GENOME_MAX_LAYERS = 4
GENOME_MIN_NEURONS = 5
GENOME_MAX_NEURONS = 10
GENOME_WEIGHTS_STD = 0.1

MUTATION_CHANCE_WEIGHT = 0.01
MUTATION_CHANCE_TOPOLOGY = 0.01
MUTATION_CHANCE_ACTIVATION = 0.02
MUTATION_NOISE_LIMIT = 0.05
MUTATION_RESIZE_LIMIT = 4

ELITISM_CUTOFF = 5